sudo: true
os:
- linux
dist: xenial
language: python
python:
- 3.8
services:
  - docker
install:
- pip install -r requirements.txt
jobs:
  include:
    - stage: lint
      script: flake8
    - stage: tests
      script:
      - coverage run -m pytest ./tests
      - coverage report -m
      name: pytest

cache:
  pip: True
  directories:
    - $HOME/dependencies
